# Use an official Python runtime as a base image
FROM python:3.9-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade /bin/bash python-api
    pip -r requirements.txt bin/bash python-api
    pip install -y openjdk-8-jdk python3-venv bin/bash python-api

# Define environment variable
ENV AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY

# Run app.py when the container launches
ENTRYPOINT ['ETL_project']
CMD ["run", "ETL_project.py"]